### ISSUE TITLE
Vocês pretende publicar o PhotoGIMP como uma extensão Flatpak para o GIMP Flatpak no Flathub?

### ISSUE THREAD

**Issue by LeandroStanger** [Diolinux/PhotoGIMP#1]
Aqui está o GMic como uma extensão Flatpak como um exemplo https://github.com/flathub/flathub/pull/1588/files

**Comment by Diolinux** [comment]
Oi Leandro, adoraria mas, não só não tenho muito tempo, mas também hoje não tenho conhecimento para isso. Se alguém desejar empacotar em Flatpak, Snap ou App Image, como ocorreu com a versão anterior, seria incrível. :)

**Comment by sudo-give-me-coffee** [comment]
@Diolinux Necessito do PR https://github.com/Diolinux/PhotoGIMP/pull/10 mas especificadamente do commit https://github.com/Diolinux/PhotoGIMP/commit/efd5f5aa5f0babceed0265223f94d67766ee1133 para empacotar o AppImage, por hora estou desenvolvendo scripts para adicionar algumas funções extras no GIMP, mas assim que o PR for aceito eu irei lançar o AppImage
