### ISSUE TITLE
[BUG] Resynthesizer not work on Windows

### ISSUE THREAD

**Issue by matheuschimelli** [Diolinux/PhotoGIMP#11]
When I was installing on Windows I tried to use the resynthesizer plugin but it did not work. I got an error message. However, I'm opening this issue to post the solution that can be useful for those who are having the same problem. 
## The solution
Install the windows version of resynthesizer from this link:
1. https://github.com/pixlsus/registry.gimp.org_static/blob/master/registry.gimp.org/files/Resynthesizer_v1.0-i686.zip
2. Copy all files that are inside the `Resynthesizer_v1.0-i686\Resynthesizer_v1.0-i686` folder into your `C:/Users/YOUR_USER/AppData/Roaming/GIMP/2.10`
3. Restart GIMP
It should work now

**Comment by tioguda** [comment]
They forgot to put the information that the patch is for 64 bits, that was the reason the plugin didn't work.

Greetings.

**Comment by sudo-give-me-coffee** [comment]
> Eles esqueceram de colocar as informações de que o patch é de 64 bits, e foi por isso que o plugin não funcionou. @Diolinux
> 
> Saudações.

Not exactly, the included resynthesizer was compiled for Linux for use with flatpak, it will not work on older Linux (distros that use glibc prior to 2.30) outside of flatpak and any other operating system

**Comment by matheuschimelli** [comment]
> They forgot to put the information that the patch is for 64 bits, that was the reason the plugin didn't work. @Diolinux
> 
> Greetings.

The true reasom the Resynthesizer plugin dont work on windows machines is related with the missing .exe inside the photogimp repo. The binaries there are only will work on linux based OS since it is not a windows executable thats why it didn't work on windows




> > Eles esqueceram de colocar as informações de que o patch é de 64 bits, e foi por isso que o plugin não funcionou. @Diolinux
> > Saudações.
> 
> Not exactly, the included resynthesizer was compiled for Linux for use with flatpak, it will not work on older Linux (distros that use glibc prior to 2.30) outside of flatpak and any other operating system

@sudo-give-me-coffee is totally right. To make it run in a OS that is not linux you must have to download the windows binaries and put inside that folder

**Comment by tioguda** [comment]
> > Eles esqueceram de colocar as informações de que o patch é de 64 bits, e foi por isso que o plugin não funcionou. @Diolinux
> > Saudações.
> 
> Not exactly, the included resynthesizer was compiled for Linux for use with flatpak, it will not work on older Linux (distros that use glibc prior to 2.30) outside of flatpak and any other operating system

Certo, na questão dos outros sistemas operacionais deve ser necessário mesmo baixar outros binários. Quanto a glibc, o Snap utiliza versões abaixo da 2.30 e funciona perfeitamente.

Saudações.

**Comment by sudo-give-me-coffee** [comment]
> Quanto a glibc, o Snap utiliza versões abaixo da 2.30 e funciona perfeitamente.
Testando no Debian Buster KDE o plugin resynthesizer não funcionou pra mim, talvez seja azar

**Comment by Diolinux** [comment]
@sudo-give-me-coffee talvez instalando o pacote gimp-plugin-registry e copiando os arquivos em python resolva, eu não sei se a versão do GIMP também a mesma de flatpak, provavelmente não seja.

**Comment by sudo-give-me-coffee** [comment]
De fato, puxando do Ubuntu 16.04 funcionou perfeitamente, aparentemente o GIMP via Snap usa a mesma lógica do GIMP AppImage

**Comment by Heart1010** [comment]
Had the same problem - here are the binaries for 32bit and 64bit (copy the correct one for your windows system to the plug-ins folder

[resynth_win_32_64.zip](https://github.com/Diolinux/PhotoGIMP/files/5062776/resynth_win_32_64.zip)
