### ISSUE TITLE
Instructions on macOS when installed with Homebrew

### ISSUE THREAD

**Issue by joaonc** [Diolinux/PhotoGIMP#14]
Similar to here https://github.com/Diolinux/PhotoGIMP/issues/4 but specifically for when Gimp is installed on macOS with Homebrew, which is a very common installer for Mac.

I tried finding where the config folder is but couldn't find it..  Does anyone know where I should look?

**Comment by Diolinux** [comment]
Hey, Davies Media Design create a tutorial to install on macOS: https://youtu.be/5nXhtaGQs9U
If anyone like to create a Homebrew script or something, that would be nice. :)
