### ISSUE TITLE
Installing on Windows 10

### ISSUE THREAD

**Issue by PinchePoncho** [Diolinux/PhotoGIMP#15]
I just try to copy in to the especified directory C:/Users/YOUR_USER/AppData/Roaming/GIMP/2.10 but nothing happens, I trying removing the dot (.) on the folders and no luck, any idea what I making wrong?

**Comment by kaltokri** [comment]
I've got the same problem. Any suggestions?

**Comment by kaltokri** [comment]
First tried with gimp version 2.10.14. Updated to 2.10.20 and still no luck.

**Comment by ChingaMiteche** [comment]
> I just try to copy in to the especified directory C:/Users/YOUR_USER/AppData/Roaming/GIMP/2.10 but nothing happens, I trying removing the dot (.) on the folders and no luck, any idea what I making wrong?

- Close gimp if it's open

- Download and extract the zip file. From the extracted folder go to the folder \.var\app\org.gimp.GIMP\config\GIMP\2.10. Highlight all in that folder then copy.

- Go to the folder C:\Users\**YOUR_USER**\AppData\Roaming\GIMP\2.10.

- You replace **YOUR_USER** with the userid that you have used to login on the computer.

- Paste the copied items to the folder

**Comment by kaltokri** [comment]
I've read and followed your installation instructions. But it has no effect.
![2020-07-01 11_29_32-2 10](https://user-images.githubusercontent.com/10243954/86228273-77ed1e00-bb8e-11ea-8e04-57858e0e3fff.png)

**Comment by rargueso** [comment]
Same problem here

**Comment by bladem2003** [comment]
Want to use on Windows, macOS or Ubuntu(Snap)?

Since it's just files, the only thing you need to do is to copy all the files that reside on a particular folder from this patch /.var/app/org.gimp.GIMP/config/GIMP/2.10 to the the GIMP's folder on each particular system, overriding the existent ones:

    Windows: C:/Users/YOUR_USER/AppData/Roaming/GIMP/2.10

**Comment by kaltokri** [comment]
Ok, now I understand it and it works.
I unzipped the file PhotoGIMP.by.Diolinux.v2020.for.Flatpak.zip in my downlods folder.
I moved in the subfolder C:\Users\xyz\Downloads\PhotoGIMP by Diolinux v2020 for Flatpak\.var\app\org.gimp.GIMP\config\GIMP\2.10.
Then I copied all folder and files, changed to %appdata%\GIMP\2.10 and paste them there. Overwrite files. Ready and works. Thx.
Sorry, I was confused by the "How to Install PhotoGIMP's Patch.txt".

**Comment by PinchePoncho** [comment]
> Ok, now I understand it and it works.
> I unzipped the file PhotoGIMP.by.Diolinux.v2020.for.Flatpak.zip in my downlods folder.
> I moved in the subfolder C:\Users\xyz\Downloads\PhotoGIMP by Diolinux v2020 for Flatpak\.var\app\org.gimp.GIMP\config\GIMP\2.10.
> Then I copied all folders and files, changed to %appdata%\GIMP\2.10 and paste them there. Overwrite files. Ready and works. Thx.
> Sorry, I was confused by the "How to Install PhotoGIMP's Patch.txt".

This works, thak you so much.

**Comment by Petr68** [comment]
How many people will be interested for Windows 10 with such a PhotoGimp installation? Can't you do it without a Linux load? Unnecessarily complicated for ordinary users.

**Comment by Diolinux** [comment]
Video tutorial for Windows: https://youtu.be/57DNUsf4A-0
