### ISSUE TITLE
What is the purpose of this hidden binary file?

### ISSUE THREAD

**Issue by Pipeliner** [Diolinux/PhotoGIMP#16]
There is a file https://github.com/Diolinux/PhotoGIMP/blob/master/.var/app/org.gimp.GIMP/.ld.so/f987e6b9bd54b82c3668251d34c8b573e1f4ba22e117ecbd1dd0013ee8320202 which seems to be unnecessary for the project. What is it used for?

**Comment by Diolinux** [comment]
Hey, i'm really not sure, i just backup the folder of GIMP in Flatpak, but it seems to be cache: https://github.com/flatpak/flatpak/issues/3365

**Comment by oplehtinen** [comment]
Installs fine without the .ld.so folder.

**Comment by emsspree** [comment]
`config/GIMP/2.10` in `.var/app/org.gimp.GIMP` is the only needed folder. Everything else is not needed.

`.ld.so` is created when running GIMP: https://manpages.debian.org/buster/manpages/ld.so.8.en.html
`current` contains only an older `org.gimp.GIMP.desktop` file.
`data` reveals some personal data!

**Comment by avlye** [comment]
These are cache files generated the first time you run Gimp.
We already removed this issue in pr #36 .

Thanks for your issue.
