### ISSUE TITLE
PhotoGIMP na versão Portable de GIMP?

### ISSUE THREAD

**Issue by MikeBlueberry** [Diolinux/PhotoGIMP#17]
Olá Diolinux, como poderei instalar o teu maravilhoso patch na versão portable do GIMP? 

Em portable, ele é mesmo stealth, não cria nem instala para a diretoria `C:/Users/YOUR_USER/AppData/Roaming/GIMP/2.10`

Uso a versão portable GIMP do portableapps.com, se essa informação for útil.

Obrigado pelo teu trabalho.

**Comment by Diolinux** [comment]
Oi Mike, olha, imagino que seja possível, mas as modificações funcionam, justamente,  através da modificação dos arquivos de configuração do GIMP, como será que a versão portable funciona neste quesito?

**Comment by emsspree** [comment]
Olá Mike.

(Let Explorer.exe show hidden files.) Find and examine the folder where you installed `GIMPPortable.exe`. In that folder there’s a `Data` folder containing a `.gimp` folder which corresponds to the `2.10` folder.

**Comment by jeffersonvidal** [comment]
> 
> 
> Olá Diolinux, como poderei instalar o teu maravilhoso patch na versão portable do GIMP?
> 
> Em portable, ele é mesmo stealth, não cria nem instala para a diretoria `C:/Users/YOUR_USER/AppData/Roaming/GIMP/2.10`
> 
> Uso a versão portable GIMP do portableapps.com, se essa informação for útil.
> 
> Obrigado pelo teu trabalho.

**Comment by jeffersonvidal** [comment]
- Primeiramente baixe o arquivo .zip do PhotoGIMP;
- Descompacte o PhotoGIMP que acabou de baixar. No meu caso a pasta ficou com o nome "PhotoGIMP-master";
- Selecione e copie todos os arquivos da pasta "PhotoGIMP-master\.var\app\org.gimp.GIMP\config\GIMP\2.10";
- Cole os arquivos na pasta "GIMPPortable\Data\.gimp";

Ao fazer esse procedimento consegui utilizar o PhotoGIMP perfeitamente na versão portable para Windows.
Espero ter ajudado.
