### ISSUE TITLE
Not working on elementary OS 5.1.6 Hera (ubuntu)

### ISSUE THREAD

**Issue by leeuwtjex** [Diolinux/PhotoGIMP#18]
Linux Juno 5.3.0-62-generic #56~18.04.1-Ubuntu SMP Wed Jun 24 16:17:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

![Screenshot from 2020-07-03 09-11-56](https://user-images.githubusercontent.com/27788737/86441797-10111180-bd0d-11ea-9767-df3344620c52.png)

![Screenshot from 2020-07-03 09-10-26](https://user-images.githubusercontent.com/27788737/86441804-12736b80-bd0d-11ea-9a39-43b323e8f136.png)

Hi team,

I tried to install your patch on gimp, it doesn't work.
The PhotoGIMP desktop icon is there and I can start gimp with it,
but I don't see any result in the GUI. If you look in these pictures, what is the photoshop element?

Also, easy fastbuttons like Ctrl +, Ctrl- are not working. 
quick export to png, I don't see it.
The buttons are grouped  different. 
How do I recognize that the PhotoGIMP gui is working?
No display comes up after starting GIMP.

Thanks for your time.

Dirk.

**Comment by leeuwtjex** [comment]
update: What is essential for me is the 'magic lasso ' function of photoshop. This scissor thing is not sufficient. Is it not possible to cover that?

**Comment by Diolinux** [comment]
Hi, the only reason for that should be you don't extract the files correctly. Is just GIMP file configurations, if you override your current ones, it should work. The patch itself is for the flatpak version, but it can be installed on any version. :)

**Comment by leeuwtjex** [comment]
Ifolowed the instructions on github. https://github.com/Diolinux/PhotoGIMP
If this is not right, could you give the instructions as for an ubuntu 18.04 pc?
These systems are technical almost the same.

**Comment by ElSamhaa** [comment]
Same on Fedora, Flatpak Gimp 2.10.

**Comment by leeuwtjex** [comment]
I have 2.10.20 here, and I installed it with Flatpak to prevent any
problems with photoGimp. Doesn't work, look at the pictures. What is wrong?

**Comment by Areidz** [comment]
I've just done the same process in Arch Linux and it isn't working for me (it changes the name, but not the UI).

I have GIMP 2.10.20 installed from flatpak.

**Comment by leeuwtjex** [comment]
Thanks Areidz! That was exactly my problem as well. I didn't realise. People should do a
'sudo apt-get --purge remove gimp'  to completely remove gimp before starting the flatpak install procedure on PhotoGIMP github. Pity there isn't much support form the developer. i like the photogimp gui, I can see the similarity, but I really miss the magic wand selector tool from photoshop, I use it a lot. You can select a subject by rotering the mouse around it. Maybe I am overlooking it, but I can't find it in PhotoGIMP. Still respect for the gui.

**Comment by elegos** [comment]
To everyone,

I've fixed the Fedora 32 (and possibly Elementary OS) issue, by installing GIMP 2.10 via the normal way (i.e. via Fedora repository), and doing the following steps:

- Remove `~/.local/share/applications/org.gimp.GIMP.desktop` (if you previously installed PhotoGIMP)
- Remove `~/.icons/photogimp.png` (if you previously installed PhotoGIMP)
- Remove `~/.var/app/org.gimp.GIMP` (if you previously installed GIMP via flatpak and / or installed PhotoGIMP)
- Uninstall flatpak's gimp via `flatpak uninstall org.gimp.GIMP` if you previously installed it via flatpak
- Install GIMP using your package manager (dnf / yum / apt / whatever)
- Start GIMP once
- Unarchive the contents of `photogimp/.var/app/org.gimp.GIMP/config/GIMP/2.10` into `~/.config/GIMP/2.10`
- Alter `~/.config/GIMP/2.10/themerc` replacing `/home/dio/` with `/home/YOUR_USERNAME/`

Enjoy

**Comment by leeuwtjex** [comment]
Elegos,

Very good detailed instruction! That is what people need when they get stuck.
Many developers in the linux world seem to forget that.
One thing is important for your instructions. Keep in mind that Fedora is belonging
to another linux family than elementary o.s. is.  
Elementary o.s. is mainly ubuntu with a beautiful desktop ui. Fedora is in the family tree
of red hat. Although all of these are cousins and share similarities, one can't assume that if a software installation removal procedure works on a fedora system, it will be automatically ok for the Debian family.
Unfortunately it doesn't work like that. 

![image](https://user-images.githubusercontent.com/27788737/91657250-e2073e00-eabf-11ea-9ac8-067303cf3e2e.png)


p.s. in the picture is only a few well known daughters listed, in reality, there are something like
600 or 700 official registered linux distributions available. Don't ask me why, I have never understood the reason for that.

**Comment by elegos** [comment]
@leeuwtjex GIMP should share the same `~/.config/GIMP/2.10` configuration folder, doesn't it? Btw I know RH is just another distro rather than Debian, though configuration folders (but particular configurations like repackagings) should be the same.
