### ISSUE TITLE
Modification of the splash photo

### ISSUE THREAD

**Issue by SauPhi** [Diolinux/PhotoGIMP#20]
Modification of the splash photo

Hello. Beyond the functioning of PhotoGIMP, there is one thing that catches my eye, it is the photo of Isabella Mariana that I find unwelcome. This blue face, covered with red blood and gagged with a butterfly, there is even better of Isabella Mariana. I think that nowadays it is necessary to look after the image of the woman. But it is a simple remark or question of taste. Sorry for my bad english.

![woman-s-face-1988681](https://user-images.githubusercontent.com/67907331/86595095-7eb5cf80-bf98-11ea-997b-c706b73e5175.jpg)

**Comment by Diolinux** [comment]
Hi, thanks for your contact. Art is a very subjective thing, I see painting, design (the photo is categorized as art by the Artist itself https://www.pexels.com/pt-br/procurar/art/). Is not blood, is just painting (is blue and green too,  and others, just like an 'aquarela'). In mythology, Butterflies are deep and powerful representations of life, cycles and beginning, maturity. I really not sure what is the purpose of the artist with this photo in particular, but as you can see, is subjective, you see what your mind wants you to see, I think (this is for me too).

I LOVE the art concept in this Photo, but i not attached to it, you can suggest another great Photo you want, or simply change it for anyone you like most, they are on the splash folder on this patch, is just a little open source project, you can change, fork a redistribute with another name, color, splash screen, etc. :+1: 

No need to be sorry for your English, is not my first language too. :+1: 

Have a nice day. :)

**Comment by poiNt3D** [comment]
It is very repulsive. Definitely scares some people off.
