### ISSUE TITLE
Release includes parts of cached user profile

### ISSUE THREAD

**Issue by oplehtinen** [Diolinux/PhotoGIMP#21]
I didn't dig deeper, but I noticed this by going to File - Open recent. Not a huge thing, but please be aware that this might reveal some personal data (username shown here).
![image](https://user-images.githubusercontent.com/7263059/86621707-55f8fe80-bfc7-11ea-9cf3-0600e4fd3776.png)

**Comment by emsspree** [comment]
The current user’s username is shown to the current user only.

**Comment by avlye** [comment]
Hi @oplehtinen , thanks for your issue.
We already removed this issue in pr #36 as part of issue #16.
If you still getting any more issue to report, please let we know.
