### ISSUE TITLE
XDG Spec ~/.icons

### ISSUE THREAD

**Issue by ElectricPrism** [Diolinux/PhotoGIMP#24]
I think you can improve on XDG spec by moving ~/.icons/photogimp.png to ~/.local/share/icons/photogimp.png

~/.icons is more a legacy directory at this point

**Comment by momentoalmir** [comment]
Hi @ElectricPrism ,

[Closing this Issue because @Diolinux  already maded this change](https://github.com/Diolinux/PhotoGIMP/tree/master/.local/share/icons).

As part of developer team of photogimp, I'm sorry we didn't tracked and answered you back 
after changing the requested improvement.
