### ISSUE TITLE
Portable install

### ISSUE THREAD

**Issue by JStyle21** [Diolinux/PhotoGIMP#25]
Hi,

Thanks for making this project, i had the same problem coming from photoshop so this makes sense, also it's cool that you can do something like this.

One small thing tho, i can understand why you would want to bundle it with things like snap and flatpak but why not offer a portable version as well?

Some of us use a custom built linux and don't want all the fancy stuff...

After looking at the release files i could see that simply copying the ./config/gimp/*VER* folder to replace my own in my install would be enough, so this is what i did.

Could you add instructions or a release for a clean version one can just apply on their own distro?

**Comment by Kreijstal** [comment]
Well, there is that guy that tried to make the appimage, https://github.com/sudo-give-me-coffee/PhotoMP/issues/7

**Comment by JStyle21** [comment]
@Kreijstal Thanks but it's not what i was looking for. flatpak, appimage, snap are all nice solutions for the basic end users of Linux but for more advanced users this is not the way.

**Comment by Kreijstal** [comment]
Uhm, how isn't that they way, didn't you want something portable?

**Comment by JStyle21** [comment]
Well, if you read my original post, you would see that i meant portable as binaries that are archived into a tar file and that's it.

Although it is true that those utilities create an independent executable image that is portable and even have some added features like security via sandboxing, the downside would be that they create a structural dependency i.e. you also need everything else in the same format so in this example since photogimp depends on gimp first, you also need gimp installed in the same way which isn't the case since my system uses the distro's package management system and i would need to reinstall gimp again just to use photogimp.

With that out of the way, sure i could build it from source but at the time i didn't want to and i ended up extracting the flatpak image and adding it manually, since it's a hack i raised this issue to ask officially to add an archived binaries release to the releases section.

**Comment by emsspree** [comment]
Hi. 

In PhotoGIMP nothing needs to be built. There’s no executeable shipped with PhotoGIMP. The only binary files are images. 

All what’s really needed is the `.var/app/org.gimp.GIMP/config/GIMP/2.10` folder which contains mainly config files.

A shell script as an installer would be nice for Unix-likes without Flatpak.

**Comment by orangemn6** [comment]
@emsspree if you really could write it, that would  be awesome!

**Comment by emsspree** [comment]
Well, I've been thinking a little about an installer. Writing a really good installer would be a bigger deal than PhotoGIMP itself. Since these are all configuration files, someone might not want to keep all of the files or someone might want to backup and restore the existing files. Since there are different flavors of the GIMP out there as well, there are also different target directories for the files. Therefore I am unfortunately convinced that the effort is not worth it. A good HOW TO is probably a better help, since all you have to do is copy files. I'm sorry to have raised expectations unnecessarily.

**Comment by JStyle21** [comment]
> Well, I've been thinking a little about an installer. Writing a really good installer would be a bigger deal than PhotoGIMP itself. Since these are all configuration files, someone might not want to keep all of the files or someone might want to backup and restore the existing files. Since there are different flavors of the GIMP out there as well, there are also different target directories for the files. Therefore I am unfortunately convinced that the effort is not worth it. A good HOW TO is probably a better help, since all you have to do is copy files. I'm sorry to have raised expectations unnecessarily.

@emsspree I agree with you, while also mentioning as i said before that including pure source files per release would also help making this faster and easier for anyone doing the manual work

**Comment by yupswing** [comment]
If somebody else look for a way to install PhotoGIMP without flatpak, here's my imperfect way of doing it. (it looks like it works, probably I am ignoring too much stuff, but, for example, I don't want my gtk configuration to be overwritten)

---

1. Download the latest version from the [Releases page](https://github.com/Diolinux/PhotoGIMP/releases) 

2. Then extract and copy the config files (if you feel like it, you can back up the original one in `~/.config/GIMP/2.10`)
```sh
\tar -xvf PhotoGIMP-1.0.tar.gz
\cp -a PhotoGIMP-1.0/.var/app/org.gimp.GIMP/config/GIMP/2.10/* ~/.config/GIMP/2.10/
\rm -rf PhotoGIMP-1.0
```

3. Uninstall (GIMP will recreate the default configuration)
```sh
\rm -rf ~/.config/GIMP/2.10
```

**Comment by JStyle21** [comment]
@momentoalmir Why did you close this issue?
The last comment was a workaround not an official fix
