### ISSUE TITLE
Problemas Na Instalação - Aparência Não Modificada

### ISSUE THREAD

**Issue by vs0uz4** [Diolinux/PhotoGIMP#30]
Segui todas as recomendações para instalação do PATCH, porém mesmo após a instalação no formato FLATPACK, e da mesclagem das pastas indicadas na minha pasta pessoal, o GIMP continuou com a mesma aparência.

O que pode ser que esteja gerando esse problema?

![Captura de tela de 2020-09-20 10-53-48](https://user-images.githubusercontent.com/2080547/93713006-9fb9a580-fb2f-11ea-8fea-0d310585552a.png)

![Captura de tela de 2020-09-20 10-55-27](https://user-images.githubusercontent.com/2080547/93713045-ec04e580-fb2f-11ea-818c-5d2d188d2bbd.png)

![Captura de tela de 2020-09-20 10-55-52](https://user-images.githubusercontent.com/2080547/93713049-f0c99980-fb2f-11ea-8e96-c66e29089a64.png)

![Captura de tela de 2020-09-20 10-56-03](https://user-images.githubusercontent.com/2080547/93713051-f4f5b700-fb2f-11ea-8b65-9c6479083661.png)

**Comment by fnxln** [comment]
Estou com o mesmo problema no meu Gentoo Kernel 5.9.8
![image](https://user-images.githubusercontent.com/20427994/99402602-49b37500-28c8-11eb-9953-a89214030161.png)
![image](https://user-images.githubusercontent.com/20427994/99402656-5768fa80-28c8-11eb-9853-e2789a4792f7.png)
O tema não aplica, nem com flatpak nem compilando com o portage

**Comment by se3d** [comment]
Também tive este problema no mint. Então vi que existe uma outra pasta de configuração. Resolvi o problema fazendo o seguinte:

Apaguei a pastinha 2.10 que tinha na pasta /.var/app/org.gimp.GIMP/config/GIMP/
Copiei o conteúdo do pacote do Diolinux na pasta /$USER/.config/GIMP  e aqui sim coloca a pasta 2.10 que ele manda colocar dentro do ./var/app...


Espero ter ajudado.

**Comment by gabrielalmir** [comment]
Olá a todos,

Parece que a discussão em torno do [assunto/tema] está inativa por um período considerável. Como não houve contribuições ou atividades recentes, decidimos encerrar esta issue.

Agradecemos o tempo e as ideias compartilhadas por todos durante esta discussão. Se ainda houver pontos relevantes a serem abordados ou se você acredita que há valor contínuo em discutir este problema, sinta-se à vontade para reabrir a issue ou iniciar um novo tópico.

Agradecemos a todos pelas contribuições e esperamos contar com a participação contínua de vocês em outras questões.

Atenciosamente
