### ISSUE TITLE
well, that thing is not working as you say ...

### ISSUE THREAD

**Issue by michaelhmich** [Diolinux/PhotoGIMP#32]
at least no on my computer, neither the flatpack method nor the copy method for normal gimp installation
furthermore I think it is a good idea not overwriting what already exist and let your history file at home because it is full with what you opened on your pc ... the gvfs uid files are also not a good idea to have in a package, last but not least you need to provide an uninstall procedure to get that things out again because it is not even near to what you describe ...

I have tried on 2.10.20 flatpack and on 2.10.18 ubuntu repo package 

System:
  Host: hm-casa Kernel: 5.8.10-hmich-tl-1.86 x86_64 bits: 64 
  Desktop: KDE Plasma 5.18.5 Distro: Linux Mint 20 Ulyana 
CPU:
  Topology: Quad Core model: AMD Phenom 9550 bits: 64 type: MCP L2 cache: 2048 KiB 
  Speed: 1100 MHz min/max: 1100/2200 MHz Core speeds (MHz): 1: 1100 2: 1100 3: 1100 
  4: 1100 
Graphics:
  Device-1: NVIDIA GK208 [GeForce GT 710] driver: nouveau v: kernel 
  Display: x11 server: X.Org 1.20.8 driver: modesetting unloaded: fbdev,vesa tty: N/A 
  OpenGL: renderer: NVD9 v: 4.3 Mesa 20.0.8

**Comment by rolodoom** [comment]
At first it didn't work for me. Then I uninstalled gimp from Ubuntu repository, the installed gimp flatpak and deleted the GIMP folder from `$HOME/.config/` and then copied the files from PhotoGIMP. This was the only way it worked. If there is a GIMP folder on `$HOME/.config/` , PhotoGIMP didn't work! Hope you could make it work!

System: Kubuntu 20.04 64 bits & GIMP 2.10.20 (Flatpak)

**Comment by workshopit** [comment]
@rolodoom  That worked for me. Thanks

**Comment by dstaksa** [comment]
@rolodoom thank you work here aswell

**Comment by Pousour** [comment]
@rolodoom worked for me, thanks :)

**Comment by Thenujan-0** [comment]
@rolodoom thanks it worked for me in manjaro
spend more than an hour trying to make it work

**Comment by gifteddiz** [comment]
@rolodoom Thank you!
This should be added to the documentation

**Comment by Aris-Eng** [comment]
This solution worked for me as well on Kubuntu, thanks for posting @rolodoom

**Comment by michaelhmich** [comment]
well, I think that shouldn't be like you say TAXSET, that is like first buying some wheels and then a car for them
it is an add-on, so then it should work as add-on and without handicapping other scripts, plugins or functions

**Comment by BenDundon** [comment]
This issue is also present in ZorinOS 16.2 (being Ubuntu-derivative) @rolodoom's solution works perfectly. Would definitely like to see this added to the docs.

**Comment by avvstrk** [comment]
worked for me :)
