### ISSUE TITLE
Adição da Instalação via gerenciador de pacotes Chocolatey para Windows

### ISSUE THREAD

**Issue by AndreAugustoAAQ** [Diolinux/PhotoGIMP#34]
Recentemente eu fiz um instalador do PhotoGIMP para Windows, utilizando o gerenciador de pacotes Chocolatey.
Gostaria de sugerir a adição deste método de instalação no README, pois pode facilitar a instalação do patch.
Sugestões e colaborações no [código do pacote](https://github.com/AndreAugustoAAQ/chocolatey-packages/tree/main/photogimp) são bem vindas
Link do pacote no repositório do Chocolatey: https://chocolatey.org/packages/photogimp/

**Comment by Kreijstal** [comment]
Seems like they need to implement the uninstaller first

**Comment by AndreAugustoAAQ** [comment]
Implementei o desinstalador 😃

**Comment by avlye** [comment]
Olá André, tudo bem?

Adorei a implementação do seu repositório Chocolatey, 
adicionei como novo método de instalação no Windows no arquivo README.

Agradeço pela sua colaboração.
