### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by 266-750Balloons** [Diolinux/PhotoGIMP#42]
I notice that this plugin lacks any license. That makes things confusing, as for example, it may not be clear what the user's limits are on a fork of this or if someone is allowed to include this in a Linux distro.
I don't think it actually infringes on any Adobe copyright, as it doesn't use Adobe assets, just makes GIMP familiar to Photoshop users. An open source license would be nice. I just want to know what I can and cannot do with the repo.

**Comment by emsspree** [comment]
[GIMP is licensed under the GPL3](https://www.gimp.org/about/COPYING). PhotoGIMP consists of only of GIMP configuration files so it has to be licensed under GPL3 as well.

**Comment by 266-750Balloons** [comment]
Issue resolved with following PR:
https://github.com/Diolinux/PhotoGIMP/pull/46/commits/3caf513493cdd0b4b65e17d1db4fdaea620dfca4
