### ISSUE TITLE
PhotoGIMP works using GIMP installation using deb ?

### ISSUE THREAD

**Issue by Augusto7743** [Diolinux/PhotoGIMP#44]
I see information about install PhotoGIMP in GIMP installed using snap.
I has GIMP installed using apt-get deb files and thus trying to figure where to replace the files from PhotoGIMP.zip in GIMP folders because not has folders in home folder that the information is saying to replace.
PhotoGIMP is compatible with GIMP installed using apt-get ?
Thanks for read and have an nice day.

**Comment by kajlando** [comment]
Just paste these files where they should be, it'll work!

**Comment by emsspree** [comment]
my [How to Install.md](https://github.com/Diolinux/PhotoGIMP/blob/01b91e878b52d435333822183290e69dce75aabf/How%20to%20Install.md)

**Comment by felipepedrosa** [comment]
Yes, It works. All you need is extract files to `~/.config/gimp/2.10` ([How to Install.md](https://github.com/Diolinux/PhotoGIMP/blob/01b91e878b52d435333822183290e69dce75aabf/How%20to%20Install.md)).

**Comment by ZurMaD** [comment]
Already forked with snap https://snapcraft.io/photogimp

**Comment by Augusto7743** [comment]
Extracted PhotoGIMP.by.Diolinux.v2020.for.Flatpak.zip

where has the folders below

icons (which has a new PhotoGIMP icon)
.local (which contains the personalized .desktop file)
.var (which contains the flatpak patch customization for GIMP 2.10+)

icons > /home/augusto/.config/GIMP/2.10/
.local > /home/.local

.var > var/app

Not works.

the folder var have several others folders that look how may be moved to others folders.
Unhappily not is simple to figure where move all files if GIMP was installed using deb files.

**Comment by Augusto7743** [comment]
I had deleted all files in ~/.config/gimp/2.10 and not works.
Not deleting all files in ~/.config/gimp/2.10 and moving var/app/org.gimp.GIMP/config/GIMP/2.10 to ~/.config/gimp/2.10 finally works.

@felipepedrosa
Thanks for reply about install.md
