### ISSUE TITLE
PhotoGIMP in the Microsoft store?

### ISSUE THREAD

**Issue by DerZombiiie** [Diolinux/PhotoGIMP#52]
I found this in the microsoft store: https://www.microsoft.com/en-us/p/gimp-photo/9mwk8qxcn72h?activetab=pivot:overviewtab
as far as i know its just some random person trying to make money with this project
*just want you to know about it

**Comment by avlye** [comment]
Hi @DerZombiiie .

Thanks for letting us know, we currently have no versions available on the Microsoft Store, so we don't recommend buying or installing from any untrusted source.

Any available installation methods are listed in the documentation (https://github.com/Diolinux/PhotoGIMP#installing-photogimp).
