### ISSUE TITLE
How To Convert A PortableApps.com Install To PhotoGIMP?

### ISSUE THREAD

**Issue by MadZiontist** [Diolinux/PhotoGIMP#63]
If you would post instructions for how to make a PortableApps.com set of folders into a PhotoGIMP build I would really appreciate it!

**Comment by emsspree** [comment]
Hi! Thanks for remembering that I rewrote the [README.md](https://github.com/emsspree/PhotoGIMP). I found it to be much too extensive and overly precise, so I left it there for the time being, didn't tell anyone about it, and then other things happened.

Here’s your How-To:
1) [Find out where your `2.10` folder equivalent is](https://github.com/emsspree/PhotoGIMP#get-gimp-dir).
2) [Copy essential config files](https://github.com/emsspree/PhotoGIMP#all-others----).
3) Enjoy Image MadZipulation.

**Comment by MadZiontist** [comment]
Hi!

First, please accept my apology for the late reply. I wanted to first see
if I had any issues before replying, so I might not be a bother with
multiple emails, and I ended up forgetting.

Anyways, I ended up getting everything essential working perfectly, really
quickly and easily. Thank you very much! :)

But, there are two files that are optional to copy over, that I wasn't able
to figure out where to put. I still would like to know where to place them.
If you wouldn't mind helping me out with that, I would greatly appreciate
it.

As far as the first file, org.gimp.GIMP.desktop:

The documentation states that it should go in $HOME/.local/share/applications/,
but I don't have any "applications" folders in my PortableApps.com setup. I
don't know if this makes any sense, but for now I threw it in a folder that
also has a file called file-desktop-link.exe in it...cause sir, this is a
Wendy's. The path to it is:

S:\PortableApps\GIMPPortable\App\gimp32\lib\gimp\2.0\plug-ins\file-desktop-link\

So after I eventually end up placing it where it should go, should I put my
path:

S:\PortableApps\GIMPPortable\GIMPPortable.exe\

next to Exec= when I edit org.gimp.GIMP.desktop?

I did use the PhotoGIMP by Diolinux v2020 for Flatpak.zip files.

Lastly, as far as the .icons/photogimp.png file is concerned, the
documentation stated to copy it to $HOME/.icons/, but I don't have any
.icons folder. I do have a few different folders called icons. I ended up
placing it in the path:

S:\PortableApps\GIMPPortable\Data\.gimp\icons\

This particular icons folder was in the same path where the GIMP console
identified that all of the other files should be placed.

My apologies if this is a lot, or if the formatting is a bother. I wasn't
sure of a better way. I know the files aren't necessary, but I really do
want to know where to place them regardless, if it's not too much trouble!

Thanks again!

-Jason

**Comment by emsspree** [comment]
Hello.

As a Windows user you don’t need the file `org.gimp.GIMP.desktop`. It is for [XDG](https://en.wikipedia.org/wiki/Freedesktop.org) compatible desktop environments like GNOME, KDE, Xfce, etc.

Windows uses [file shortcuts (`*.LNK`)](https://en.wikipedia.org/wiki/Shortcut_(computing)#Microsoft_Windows) instead.

You also don’t need the `photogimp.png` image file. If you want you could convert it to an `*.ICO` file and set it as a shortcut’s icon. But GIMP will not use it.

The folder `S:\PortableApps\GIMPPortable\Data\.gimp\icons\` is for icons used by GIMP’s GUI, [see here](https://daviesmediadesign.com/customize-gimp-2-10-user-interface/).

Have fun!

**Comment by MadZiontist** [comment]
Thanks! I really appreciate your help.

-Jason
