### ISSUE TITLE
Photogimp does not work

### ISSUE THREAD

**Issue by Marbin-W** [Diolinux/PhotoGIMP#64]
Followed carefully your Instruction.
Installed Gimp out of Flatpak started and cloased Gimp copied the folders but when i start Photogimp it shows the old GUI.

Kubuntu 21.10

**Comment by emsspree** [comment]
Hi.

make sure `$HOME/.config/GIMP/2.10` does not exsist.

[Here’s another how-to](https://github.com/emsspree/PhotoGIMP#get-gimp-dir).

**Comment by Marbin-W** [comment]
Did work
