### ISSUE TITLE
Please export with "System language" as the interface setting

### ISSUE THREAD

**Issue by getsnoopy** [Diolinux/PhotoGIMP#69]
It seems like you made a snapshot of the configuration with the language set to `English [en_US]`, which a minority of the world uses. It would be much better to export it with the `System Language` setting set so that it automatically starts up in whatever locale the user has their system set to, which for my case (and most English users around the world) will be `English [en_GB]`.

**Comment by galmirpr** [comment]
Sure, I can't do a major release right now, but I released a [minor upgrade with latest commit from 2020 version](https://github.com/Diolinux/PhotoGIMP/releases/tag/1.1).
This means that you will still have auxiliary third-party installation projects being low on the previous version, but the project will distribute the current version as default on Github.
