### ISSUE TITLE
Não consigo instalar.

### ISSUE THREAD

**Issue by Rtmorais** [Diolinux/PhotoGIMP#7]
Boa noite, tudo bom?

Fiz tudo como solicitado por vocês na instalação, mas não funcionou.

O icone e nome modificaram, mas nada alem disso. A splash screen continua a do GIMP e o design do app também. Sabem porque pode ser isso?

Obrigado

**Comment by Diolinux** [comment]
Oi, provavelmente você não extraiu corretamente os arquivos. Este patch é para o GIMP em flatpak especificamente, você talvez esteja utilizando de outra forma?

Caso você esteja usando Snap, .deb (ou outro formato), você precisa sobrescrever as pastas do GIMP com os arquivos do Patch, a localização deve ser diferente.

Temos o nosso fórum também para tirar dúvidas: https://plus.diolinux.com.br

**Comment by tioguda** [comment]
Como citado pelo @Diolinux , você deve ter extraído os arquivos nos lugares errados, o patch funciona em qualquer formato de empacotamento, desde que seja extraído nos lugares corretos. Eu testei o funcionamento no Manjaro, e funcionou com o GIMP empacotado de forma nativa,  em Snap, em Flatpak e em AppImage.

Saudações.

**Comment by Rtmorais** [comment]
Obrigado aos dois. 

Sim, aparentemente tinha extraído mal as pastas. 

Tinha feito com o empacotamento de. Flat, mas não foi. 

Deletei tudo, instalei gimp pelo snap e substitui as pasta corretas e agora funciona perfeitamente. 

Muito obrigado.
