### ISSUE TITLE
Photogimp opens, but whitout any fonts and then crashes

### ISSUE THREAD

**Issue by HTMLDevelopment** [Diolinux/PhotoGIMP#75]
![image](https://user-images.githubusercontent.com/82397029/183844003-d0f98942-321b-4e6b-bf82-d31a4fce1ed6.png)
after trying to install photogimp for a long time, i was finally able to install it using Snap, the icon appeared at the menu of KDE and when I opened it, it was the loading screen of Photogimp, but what should be text was just these white boxes, after loading, photogimp crashes, can anyone help me please? Thanks in advance.

**Comment by Diolinux** [comment]
Hi! :)

The snap version has no direct relationship with the main project. So it may be a problem with this particular version, maybe is useful to talk with its creator. 

Our patch, is originally tested against the flatpak version of GIMP, have tried it yet?

Best wishes :+1:

**Comment by HTMLDevelopment** [comment]
Well, first time i tried to install it, I used the flatpak version of GIMP, also installing photogimp files, however, it didn't work

**Comment by emsspree** [comment]
0. quit GIMP
1. remove/rename …
    * `"$HOME/.var/app/org.gimp.GIMP/config/GIMP/2.10"`
    * `"$HOME/snap/gimp/47/.config/GIMP/2.10"`
    * `"$HOME/.config/GIMP/2.10"`
2. start GIMP, quit GIMP.
3. re-install PhotoGIMP ([try this](https://github.com/emsspree/PhotoGIMP/blob/new_HowTo/README.md))

**Comment by HTMLDevelopment** [comment]
@emsspree alright, I will try this next time I boot into my Linux, thanks
