### ISSUE TITLE
[Request] Add shortcut for scale

### ISSUE THREAD

**Issue by PaulDotSH** [Diolinux/PhotoGIMP#77]
Hi, the shortcut for scale could be added as CTRL+T (similar to photosohp's transform shortcut)

**Comment by lucasgabmoreno** [comment]
> Hi, the shortcut for scale could be added as CTRL+T (similar to photosohp's transform shortcut)

It's done:
```
(gtk_accel_path "<Actions>/tools/tools-scale" "<Primary>t")
```

Try select something and Ctrl+T
