### ISSUE TITLE
Add compatibility with Windows?

### ISSUE THREAD

**Issue by lfelipe1501** [Diolinux/PhotoGIMP#8]
Is it possible to have a compatibility with Windows?

**Comment by Diolinux** [comment]
Hi, yes. In fact, i think is probably already work, you just need to copy the files from .var/app/org.gimp.GIMP/config/GIMP/2.10 inside your GIMP's folder on Windows, i guess is on C:\Users\{your_id}\.gimp-2.10 or something like that :)

**Comment by cheesemarathon** [comment]
I have just copied the contents of `.var/app/org.gimp.GIMP/config/GIMP/2.10` into `C:\Program Files\GIMP 2\share\gimp\2.0` as I don't have a gimp folder in my user directory. Do I need to make a folder in my user directory, is there somewhere else I need to be putting these files?

Some more detailed instructions for Windows in the ReadMe would be useful.

**Comment by tioguda** [comment]
@cheesemarathon you must have GIMP installed and have started it at least once. After that you extract the files in the folder, overwriting the existing ones.

Greetings

**Comment by cheesemarathon** [comment]
> 
> 
> @cheesemarathon you must have GIMP installed and have started it at least once. After that you extract the files in the folder, overwriting the existing ones.
> 
> Greetings

I did exactly that, extracted the files in `.var/app/org.gimp.GIMP/config/GIMP/2.10` overwriting any existing files in `C:\Program Files\GIMP 2\share\gimp\2.0` but only after running gimp once.

I am assuming it hasn't installed as the layout has not changed and after selecting something and hitting `Ctrl+D` it duplciates the file rather than deselects the selection.

**Comment by RailRanger** [comment]
Yeah unfortunately it's not quite clear how to install it in Windows as the directories don't align very well as far as i can tell.

**Comment by Diolinux** [comment]
@RailRanger hi, we create a blog post about the new release: https://diolinux.com.br/2020/06/photogimp-2020.html
The Windows directory is C:/Users/YOUR_USER/AppData/Roaming/GIMP/2.10

Just copy all the files inside the folder .var/app/org.gimp.GIMP/config/GIMP/2.10  from the patch and paste in the Windows folder (above indicated) overwriting every file. That should do the trick. :)

**Comment by cheesemarathon** [comment]
> @RailRanger hi, we create a blog post about the new release: https://diolinux.com.br/2020/06/photogimp-2020.html
> The Windows directory is C:/Users/YOUR_USER/AppData/Roaming/GIMP/2.10
> 
> Just copy all the files inside the folder .var/app/org.gimp.GIMP/config/GIMP/2.10 from the patch and paste in the Windows folder (above indicated) overwriting every file. That should do the trick. :)

Thanks for this.  I can confirm it works now. Close the issue?
