### ISSUE TITLE
Plug-ins don't work in windows

### ISSUE THREAD

**Issue by xdanielc** [Diolinux/PhotoGIMP#83]
Current Gimp version is 2.10.32
When I try some plug-ins like map >resynthesize it says is not found.
I had previously installed gimp 2.10.30, a normal instalation.

Plug-in will be searched in location
C:\Users\<user>\AppData\Roaming\GIMP\2.10\plug-ins\resynthesizer_gui

Actually there's a file there, but in windows, files without extension are probably not used?

**Comment by momentoalmir** [comment]
Hello @xdanielc ,

I'm sorry for the problems you've been facing with the plugins included in the project. Currently the plugins compiled to the project are intended for native support on Linux. For now, it is necessary to manually add the desired Windows-compatible plugins inside the `plug-ins` folder of the project.

It is within our change plans for the project to adapt these scenarios for the main operating systems. (See: [](https://github.com/Diolinux/PhotoGIMP/issues/66)).

Best regards.
