### ISSUE TITLE
Setup PhotoGIMP on OSX bash

### ISSUE THREAD

**Issue by MatthijsKamstra** [Diolinux/PhotoGIMP#84]
This is not an issue, but a small addition to your AWESOME project.

I recently stopped using Photoshop and came across this project and had to try it.

Also, I am very lazy, so I made an install bash script: https://github.com/MatthijsKamstra/Mac-setup/blob/master/install/photogimp_osx.sh

## what does it do?

- osx
- gimp needs to be installed (brew or otherwise)
- download zip
- installs the correct folder
- creates an icon
- installs icon
- deletes all files generated/downloaded

## run bash 

you can download and run the [bash script](https://raw.githubusercontent.com/MatthijsKamstra/Mac-setup/master/install/photogimp_osx.sh): 

```bash
cd /path/to/download/folder
sh photogimp_osx.sh
```

## easy install

even lazier:

```bash
sh -c "$(curl -fsSL https://raw.githubusercontent.com/MatthijsKamstra/Mac-setup/master/install/photogimp_osx.sh)"
```

## feel free to add to your own repo

or let me know if I need to make a pullrequest

**Comment by momentoalmir** [comment]
Hello @MatthijsKamstra ,

Sorry if I'm late, but I added as another option to setup PhotoGIMP in MacOS.
I highly appreciate your collaboration on the project.
Since a pull request was not made, I gave you proper credit in the title of the README.md.

best regards 😊
