### ISSUE TITLE
[Request] Add Layer and Color Dialog Shorcut

### ISSUE THREAD

**Issue by lucasgabmoreno** [Diolinux/PhotoGIMP#86]
Adobe Photoshop uses F6 and F6.
Just change these lines into menurc:
```
(gtk_accel_path "<Actions>/dialogs/dialogs-colors" "F6")
(gtk_accel_path "<Actions>/dialogs/dialogs-layers" "F7")
```
PhotoGIMP is awesome!
Thanks!

**Comment by momentoalmir** [comment]
Added on [commit#e75ce2eb5798167383b2df88ccb0e91475b6f8a8](https://github.com/Diolinux/PhotoGIMP/commit/e75ce2eb5798167383b2df88ccb0e91475b6f8a8).
Thanks for your request.
